---
- name: Validate inputs
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Validate TARGET_SERVICES
      fail:
        msg: "ERROR: ต้องระบุ TARGET_SERVICES ก่อน deploy"
      when: lookup('env', 'TARGET_SERVICES') == ''

- name: "Deploy services to {{ env | default('') }}"
  hosts: >-
    {{ lookup('env', 'TARGET_SERVICES').split(',')
       | map('replace', '-', '_')
       | map('regex_replace', '$', '_servers')
       | join(':') }}
  serial: 0
  any_errors_fatal: true

  vars:
    image_tag: "{{ lookup('env', 'IMAGE_TAG') }}"
    jar_src: "{{ lookup('env', 'JAR_SRC') }}"

  tasks:
    - name: "[ {{ env | upper }} ] Deploy each service"
      include_role:
        name: "{{ 'deploy_systemd' if item.value.type | default('docker') == 'systemd' else 'deploy_docker' }}"
      vars:
        service_name: "{{ item.key }}"
        svc: "{{ item.value }}"
      when: item.key in (target_services | default('')).split(',')
      loop: "{{ services | dict2items }}"
      loop_control:
        label: "{{ item.key }}"
