---
- name: Validate inputs
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Validate TARGET_HOST
      fail:
        msg: "ERROR: ต้องระบุ TARGET_HOST ก่อน deploy"
      when: lookup('env', 'TARGET_HOST') == ''

- name: "Deploy Grafana Alloy to {{ lookup('env', 'TARGET_HOST') }}"
  hosts: "{{ lookup('env', 'TARGET_HOST') }}"
  serial: 0
  any_errors_fatal: true
  roles:
    - deploy_alloy
