---
- name: "Rollback services on {{ env }}"
  hosts: app_servers
  serial: 0
  any_errors_fatal: true

  vars:
    cli_target_services: "{{ lookup('env', 'TARGET_SERVICES') }}"
    rollback_tag: "{{ lookup('env', 'ROLLBACK_TAG') }}"

  tasks:
    - name: Validate ROLLBACK_TAG
      fail:
        msg: "ERROR: ต้องระบุ ROLLBACK_TAG ก่อน rollback"
      when: rollback_tag == ''
      run_once: true

    - name: "[ {{ env | upper }} ] Rollback each service"
      include_role:
        name: deploy_docker
      vars:
        service_name: "{{ item.key }}"
        svc: "{{ item.value }}"
        image_tag: "{{ rollback_tag }}"
      when: >-
        (cli_target_services != '' and (cli_target_services == 'all' or item.key in cli_target_services.split(',')))
        or
        (cli_target_services == '' and (target_services | default('all') == 'all' or item.key in (target_services | default('all')).split(',')))
      loop: "{{ services | dict2items }}"
      loop_control:
        label: "{{ item.key }}"
