[app_servers]
uat-app01 ansible_host=10.200.120.20
uat-app02 ansible_host=10.200.120.21
[app_servers:vars]
ansible_user=adminos

[customer_portal_be_servers]
uat-server1 ansible_host=10.200.120.130 target_services=customer-portal-be
[customer_portal_be_servers:vars]
ansible_user=adminos

[rest_pdf_servers]
uat-restpdf01 ansible_host=10.200.120.131 target_services=rest-pdf
[rest_pdf_servers:vars]
ansible_user=adminos

[rest_hsm_servers]
uat-restpdf01 ansible_host=10.204.61.40 target_services=rest-hsm
[rest_hsm_servers:vars]
ansible_user=adminos

[service_servers:children]
customer_portal_be_servers
rest_pdf_servers
rest_hsm_servers

