[app_servers]
uat-server1 ansible_host=192.168.1.10
uat-server2 ansible_host=192.168.1.11
uat-server3 ansible_host=192.168.1.12
uat-server4 ansible_host=192.168.1.13

[app_servers:vars]
ansible_user=deploy
ansible_ssh_private_key_file=/opt/teamcity/deploy_key
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
