[app_servers]
uat-app01 ansible_host=10.200.120.20
uat-app02 ansible_host=10.200.120.21
[app_servers:vars]
ansible_user=adminos

[app_v2_servers]
uat-server1 ansible_host=10.200.120.130
[app_v2_servers:vars]
ansible_user=adminos

[rest_pdf_servers]
uat-restpdf01 ansible_host=10.200.120.131
[rest_pdf_servers:vars]
ansible_user=adminos

[rest_hsm_servers]
uat-restpdf01 ansible_host=10.204.61.40
[rest_hsm_servers:vars]
ansible_user=adminos

