[nginx_servers]
prod-nginx01 ansible_host=10.200.120.51
prod-nginx02 ansible_host=10.200.120.52
[nginx_servers:vars]
ansible_user=adminos
node_group=NGINX

[app_v1_servers]
prod-appv1-server1 ansible_host=10.200.120.11
[app_v1_servers:vars]
ansible_user=adminos
node_group=ETAX-NG-V1

[app_v2_servers]
prod-server1 ansible_host=10.200.120.65
prod-server2 ansible_host=10.200.120.66
[app_v2_servers:vars]
ansible_user=adminos
node_group=ETAX-NG

[rest_pdf_servers]
prod-restpdf01 ansible_host=10.200.120.61
prod-restpdf02 ansible_host=10.200.120.62
[rest_pdf_servers:vars]
ansible_user=adminos
node_group=REST-PDF

[haproxy_servers]
prod-haproxy-01 ansible_host=10.204.61.61
prod-haproxy-02 ansible_host=10.204.61.62
[haproxy_servers:vars]
ansible_user=adminos
node_group=HA-PROXY

[rest_hsm_servers]
prod-resthsm01 ansible_host=10.204.61.65
prod-resthsm02 ansible_host=10.204.61.66
[rest_hsm_servers:vars]
ansible_user=adminos
node_group=REST-HSM
