[app_servers]
prod-server1 ansible_host=192.168.2.10
prod-server2 ansible_host=192.168.2.11
prod-server3 ansible_host=192.168.2.12
prod-server4 ansible_host=192.168.2.13

[app_servers:vars]
ansible_user=deploy
ansible_ssh_private_key_file=/opt/teamcity/deploy_key
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
