[app_servers]
prod-app01 ansible_host=10.200.120.11
prod-app02 ansible_host=10.200.120.12
prod-app03 ansible_host=10.200.120.13
prod-app04 ansible_host=10.200.120.14
[app_servers:vars]
ansible_user=adminos

[customer_portal_be_servers]
prod-server1 ansible_host=10.200.120.17 target_services=customer-portal-be
[customer_portal_be_servers:vars]
ansible_user=adminos

[rest_pdf_servers]
prod-restpdf01 ansible_host=10.200.120.61 target_services=rest-pdf
prod-restpdf02 ansible_host=10.200.120.62 target_services=rest-pdf
[rest_pdf_servers:vars]
ansible_user=adminos

[rest_hsm_servers]
prod-restpdf01 ansible_host=10.204.61.65 target_services=rest-hsm
prod-restpdf02 ansible_host=10.204.61.66 target_services=rest-hsm
[rest_hsm_servers:vars]
ansible_user=adminos

[service_servers:children]
customer_portal_be_servers
rest_pdf_servers
rest_hsm_servers

