[nginx_servers]
uat-nginx01 ansible_host=10.200.120.141
[nginx_servers:vars]
ansible_user=adminos
node_group=NGINX

[app_v2_servers]
uat-server1 ansible_host=10.200.120.129
uat-server2 ansible_host=10.200.120.130
[app_v2_servers:vars]
ansible_user=adminos
node_group=ETAX-NG

[rest_pdf_servers]
uat-restpdf01 ansible_host=10.200.120.131
[rest_pdf_servers:vars]
ansible_user=adminos
node_group=REST-PDF

[haproxy_servers]
uat-haproxy-01 ansible_host=10.204.61.51
[haproxy_servers:vars]
ansible_user=adminos
node_group=HA-PROXY


[rest_hsm_servers]
uat-resthsm01 ansible_host=10.204.61.40
[rest_hsm_servers:vars]
ansible_user=adminos
node_group=REST-HSM
