---
- name: Install alloy via Docker
  ansible.builtin.include_tasks: install_docker.yml
  when: deploy_type | default('docker') == 'docker'

- name: Install alloy via systemd
  ansible.builtin.include_tasks: install_systemd.yml
  when: deploy_type | default('docker') == 'systemd'
